Add Vale to the pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,10 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+if ! command -v vale &> /dev/null; then
+  echo "vale could not be found."
+  echo "Please make sure it's installed on your system: https://vale.sh/docs/vale-cli/installation/"
+  exit 1
+fi
+
 yarn run lint-staged
